### PR TITLE
Enable packaging with briefcase

### PR DESCRIPTION
**Pull request by AbdulkadirA**
This PR enables packaging installers for Linux, Windows, and macOS.

- [x] Windows 10/11
- [x] macOS
- [ ] Linux | will be addressed in the future

### CODE REVIEW

**Comment by AbdulkadirA** [comment]
The installation package can be built as follows (tested on Windows 11)

```shell
git clone https://github.com/CBICA/NiBAx.git
cd NiBAx
git fetch origin refs/pull/166/head
git checkout -b briefcase FETCH_HEAD
python -m venv .env
source .env/bin/activate
python -m pip install -U pip briefcase
python -m pip install -U MarkupSafe==2.0.1
briefcase create
briefcase build
briefcase run # will open the application, close to continue
briefcase package
```

The installer will appear in the `windows` subfolder. For `macOS` and Linux, the installers will appear in the `linux` and `macOS` subfolders, respectively.

**Comment by melhemr** [comment]
@AbdulkadirA this happened at briefcase package, and it happened again after ```briefcase package --no-sign```.  Should I just install the package?

**Comment by AbdulkadirA** [comment]
> And the icon for the NiBAx app is a bumblebee. Is this correct?

@melhemr Yes, this is expected. Can you install (move to Applications folder) and run NiBAx by double-clicking it?

**Comment by AbdulkadirA** [comment]
@melhemr I updated the description and marked the PR as ready for review. Thanks.

**Review by melhemr — APPROVED** [review]
Works

**Pull request merged**
